name: InfusedEffects
author: Dxzo
main: com.dxzo.bukkit.InfusedEffects.InfusedEffects
version: 2.0

commands:
  addeffect:
    usage: /addeffect <effect type> <level> <duration> [-wear]
    description: Add an effect to an item. Adding -wear to the end makes the effect get applied when you wear the item.
    aliases: [adde]
  deleffect:
    usage: /deleffect <effect type|all> [-wear]
    description: Delete an effect from an item. Adding -wear makes it delete wearable effects.
    aliases: [dele]
  reloadtfx:
    usage: /reloadtfx
    description: reloads InfusedEffects
    aliases: []
permissions:
  infusedeffects.command.addeffect.*:
    default: false
  infusedeffects.command.deleffect:
    default: false
  infusedeffects.command.reload:
    default: false
  infusedeffects.use.weapon:
    default: false
  infusedeffects.use.food:
    default: false
  infusedeffects.use.wear:
    default: false
  infusedeffects.use.armor:
    default: false
  infusedeffects.command.*:
    default: false
    children:
      infusedeffects.command.addeffect.*: true
      infusedeffects.command.deleffect: true
  infusedeffects.use.*:
    default: false
    children:
      infusedeffects.use.weapon: true
      infusedeffects.use.food: true
      infusedeffects.use.wear: true
      infusedeffects.use.armor: true
  infusedeffects.*:
    default: op
    children:
      infusedeffects.use.*: true
      infusedeffects.command.*: true
