name: ToolAndFoodFX
main: com.gmail.brandonli2010.ToolAndFoodFX.ToolAndFoodFX
version: 1.4
description: A plugin that lets you add multiple effects to food, tools, weapons, and armor
author: thepowderguy
website: 'http://dev.bukkit.org/bukkit-plugins/toolandfoodfx/'
commands:
  addeffect:
    usage: /addeffect <effect type> <level> <duration> [-wear]
    description: Add an effect to an item. Adding -wear to the end makes the effect get applied when you wear the item.
    aliases: [adde]
  deleffect:
    usage: /deleffect <effect type|all> [-wear]
    description: Delete an effect from an item. Adding -wear makes it delete wearable effects.
    aliases: [dele]
permissions:
  toolandfoodfx.command.addeffect.*:
    default: false
  toolandfoodfx.command.deleffect:
    default: false
  toolandfoodfx.use.weapon:
    default: false
  toolandfoodfx.use.food:
    default: false
  toolandfoodfx.use.wear:
    default: false
  toolandfoodfx.use.armor:
    default: false
  toolandfoodfx.command.*:
    default: false
    children:
      toolandfoodfx.command.addeffect.*: true
      toolandfoodfx.command.deleffect: true
  toolandfoodfx.use.*:
    default: false
    children:
      toolandfoodfx.use.weapon: true
      toolandfoodfx.use.food: true
      toolandfoodfx.use.wear: true
      toolandfoodfx.use.armor: true
  toolandfoodfx.*:
    default: op
    children:
      toolandfoodfx.use.*: true
      toolandfoodfx.command.*: true
